WEB_Assignment_Team4/Models/SubmissionViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;


namespace WEB_Assignment_Team4.Models
{
    public class SubmissionViewModel
    {
        public int CompetitorID { get; set; }
        public string Salutation { get; set; }
        [Display(Name = "Competitor Name")]
        public string CompetitorName { get; set; }
        [Display(Name = "Email")]
        public string EmailAddr { get; set; }
        public int CompetitionID { get; set; }
        [Display(Name = "File Name")]
        public string FileName { get; set; }
        [Display(Name = "Upload Time")]
        public DateTime? UploadDateTime { get; set; }
        public string Appeal { get; set; }
        [Display(Name = "Vote Count")]
        public int VoteCount { get; set; }
        public double Score { get; set; }
        public int? Ranking { get; set; }
    }
}

WEB_Assignment_Team4/Models/Submissions.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using WEB_Assignment_Team4.DAL;
using WEB_Assignment_Team4.Models;

namespace WEB_Assignment_Team4.Models
{
    public class Submissions
    {
        [Display(Name = "CompetitionID")]
        public int? CompetitionID { get; set; }

        [Display(Name = "CompetitorID")]
        public int CompetitorID { get; set; }

        [Display(Name = "File Name")]
        public string FileName { get; set; }

        [Display(Name = "Date and time of file upload")]
        [DataType(DataType.Date)]
        public DateTime? UploadDateTime { get; set; }

        [StringLength(255)]
        public string Appeal { get; set; }

        [Display(Name = "Total votes")]
        public int VoteCount { get; set; }

        [Display(Name = "Ranking")]
        public int? Ranking { get; set; }

        public List<Submissions> submissionsList { get; set; }
        public Submissions()
        {
            submissionsList = new List<Submissions>();
        }
    }
}

WEB_Assignment_Team4/Controllers/SubmissionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WEB_Assignment_Team4.DAL;
using WEB_Assignment_Team4.Models;

namespace WEB_Assignment_Team4.Controllers
{
    public class SubmissionsController : Controller
    {
        private SubmissionsDAL submissionContext = new SubmissionsDAL();

        // GET: SubmissionsController

        public ActionResult Index(int? id)
        {
            Submissions submissions = new Submissions();
            submissions.submissionsList = submissionContext.GetAllSubmissions();
            // Check if BranchNo (id) presents in the query string
            string voteStatus = HttpContext.Session.GetString("voteStatus");
            if (voteStatus == null)
            {
                if (id != null)
                {
                    ViewData["selectedCompetition"] = id.Value;
                    // Get list of staff working in the branch
                    submissions.submissionsList = submissionContext.GetCompetitionSubmissions(id.Value);
                }
                else
                {
                    ViewData["selectedCompetition"] = "";
                }
                return View(submissions);
            }
            else
            {
                ViewData["selectedCompetition"] = id.Value;
                TempData["Message"] = "Thank you for voting! Vote again next time";
                return View(submissions);
            }
        }

        // GET: SubmissionsController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: SubmissionsController/Create
        public ActionResult Create()
        {
            return View();
        }

        public ActionResult Select()
        {
            return View();
        }


        // POST: SubmissionsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: SubmissionsController/Edit/5

        public ActionResult Edit(int competitionID, int competitorID)
        {
            string voteStatus = HttpContext.Session.GetString("voteStatus");
            if(voteStatus == null)
            {
                ViewData["SubmissionList"] = submissionContext.GetAllSubmissions();
                if (ModelState.IsValid)
                {
                    //Update staff record to database
                    submissionContext.IncreaseCount(competitionID, competitorID);
                    HttpContext.Session.SetString("voteStatus", "Voted");
                    TempData["Message"] = "Thank you for voting! Vote again next time";
                    return RedirectToAction("Index", new { id = competitionID });
                }
                else
                {
                    //Input validation fails, return to the view
                    //to display error message
                    return RedirectToAction("Index", new { id = competitionID });
                }
            }
            else
            {
                return RedirectToAction("Index", new { id = competitionID });
            }
        }

        // GET: SubmissionsController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: SubmissionsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

WEB_Assignment_Team4/Views/Submissions/Index.cshtml
@model WEB_Assignment_Team4.Models.Submissions

@{
    ViewData["Title"] = "Index";
}

<br />
<h4 class="PageTitle">View submissions</h4>
<h5>View and vote for submissions. </h5>
<div>
    <a asp-action="List" asp-controller="Competition" asp-route-id="@ViewData["selectedCompetition"]">Back to List</a>
</div>
<!-- Add a partial view to display a list of interest records
     in a tabular format. -->
<partial name="~/Views/submissions/_ViewSubmissions.cshtml" model="@Model" />

WEB_Assignment_Team4/Views/Submissions/_ViewSubmissions.cshtml
@model WEB_Assignment_Team4.Models.Submissions

<br />
<h4 class="PageTitle">Submissions</h4>
@if (Model.submissionsList.Count > 0)
{
    <div class="table-responsive">
        <table id="viewSubmission" class="table table-striped table-bordered table-hover">
            <thead>
                <tr>
                    <th>CompetitorID</th>
                    <th>Upload Date</th>
                    <th>File Name</th>
                    <th>Vote Count</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var items in Model.submissionsList)
                {
                    <tr>
                        <td>@items.CompetitorID</td>
                        <td>@items.UploadDateTime</td>
                        <td>@items.FileName</td>
                        <td>@items.VoteCount</td>

                        <td>
                            @{
                                string voteStatus = Context.Session.GetString("voteStatus");
                                if (voteStatus == null)
                                {
                                    <a asp-action="Edit" asp-controller="Submissions"
                                       asp-route-competitionID="@items.CompetitionID"
                                       asp-route-competitorID="@items.CompetitorID"
                                       class="btn btn-warning rounded-pill mr-2">Vote</a>
                                }
                                else
                                {
                                    <span style="color:red;">@TempData["Message"]</span>
                                }
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}
else
{
    <span style="color:red;">No Submissions Found!</span>
}